services:
  init-elasticsearch:
    image: ghcr.io/medizininformatik-initiative/dataportal-es-init:latest
    # Please see the README.md description of the ES_HOST parameter concerning the network_mode
    network_mode: host
    environment:
      ES_HOST: ${ELASTIC_INIT_ES_HOST}
      ES_PORT: ${ELASTIC_INIT_ES_PORT}
      ONTO_GIT_TAG: ${ELASTIC_INIT_ONTO_GIT_TAG}
      ONTO_REPO: ${ELASTIC_INIT_ONTO_REPO}
      DOWNLOAD_FILENAME: ${ELASTIC_INIT_DOWNLOAD_FILENAME}
      FORCE_REINSTALL: ${ELASTIC_INIT_FORCE_REINSTALL}
#    volumes:
#      - type: bind
#        source: /tmp/elastic.zip
#        target: /tmp/mounted_onto.zip
#        read_only: true