services:
  init-elasticsearch:
    image: dataportal-es-init:1.0.0
    network_mode: host
    environment:
      ES_HOST: ${ELASTIC_INIT_ES_HOST}
      ES_PORT: ${ELASTIC_INIT_ES_PORT}
      ONTO_GIT_TAG: ${ELASTIC_INIT_ONTO_GIT_TAG}
      ONTO_REPO: ${ELASTIC_INIT_ONTO_REPO}
      ONTO_RELATIVE_PATH: ${ELASTIC_INIT_ONTO_RELATIVE_PATH}
      DOWNLOAD_FILENAME: ${ELASTIC_INIT_DOWNLOAD_FILENAME}
      EXIT_ON_EXISTING_INDICES: ${ELASTIC_INIT_EXIT_ON_EXISTING_INDICES}
      FORCE_INDEX_CREATION: ${ELASTIC_INIT_FORCE_INDEX_CREATION}