name: Daily Untagged Image Cleanup
permissions: read-all
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
jobs:
  delete-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f # v1
